import "bootstrap/dist/css/bootstrap.min.css";
import './globals.css'
import { Inter } from 'next/font/google'
import Header from "../../components/header";
import LeftAside from "../../components/leftAside";
import Rightaside from "../../components/rightAside";
import Footer from "../../components/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main class="row p_tbdr">
          <LeftAside></LeftAside>
            {children}         
          <Rightaside></Rightaside>
        </main>
        <Footer></Footer>
      </body>
    </html>
  )
}
